# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/master/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys

sys.path.insert(0, os.path.abspath("../.."))

from foxes_opt import __version__

# -- Project information -----------------------------------------------------

project = "foxes-opt"
copyright = "2026, Fraunhofer IWES"
author = "Fraunhofer IWES"

# The short X.Y version
version = __version__
# The full version, including alpha/beta/rc tags
release = __version__


# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    # "nbsphinx",
    "sphinx_immaterial",
    "sphinx_immaterial.apidoc.python.apigen",
    "sphinx.ext.autodoc",
    "sphinx.ext.autosectionlabel",
    # "sphinx.ext.autosummary",
    "sphinx.ext.intersphinx",
    "sphinx.ext.mathjax",
    # "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
    # "sphinx.ext.inheritance_diagram",
    "sphinx.ext.doctest",
    "m2r2",
    "myst_nb",
]

intersphinx_mapping = {
    "python": ("https://docs.python.org/3/", None),
    "numpy": ("https://docs.scipy.org/doc/numpy/", None),
    "scipy": ("https://docs.scipy.org/doc/scipy/reference/", None),
}

# Add any paths that contain templates here, relative to this directory.
# templates_path = ["_templates"]
# autosummary_generate = False

# The suffix(es) of source filenames.
#
source_suffix = {
    ".rst": "restructuredtext",
    ".md": "restructuredtext",
    ".ipynb": "myst-nb",
    ".myst": "myst-nb",
}

# The master toctree document.
master_doc = "index"

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = [
    "build",
    "Thumbs.db",
    ".DS_Store",
    "**.ipynb_checkpoints",
    # "_templates/*",
    # DEBUG
    # "examples.rst",
    # "notebooks/*",
    # "notebooks/layout_opt.ipynb",
    # "notebooks/timelines.ipynb",
    # "notebooks/heterogeneous.ipynb",
    # "notebooks/timeseries.ipynb",
    # "api.rst"
]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = None

# autosummary_generate = True
napolean_use_rtype = False

# -- Options for sphinxcontrib.email ------------------------------------------
# email_automode = True


# Additional files needed for generating LaTeX/PDF output:
# latex_additional_files = ['references.bib']

# -- Options for autodoc ----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#configuration

# Automatically extract typehints when specified and place them in
# descriptions of the relevant function/method.
autodoc_typehints = "description"

# Don't show class signature with the class' name.
autodoc_class_signature = "separated"

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "sphinx_immaterial"

# html_theme = 'cloud'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
html_theme_options = {
    # TOC options
    #'navigation_depth': 2,  # only show 2 levels on left sidebar
    # "collapse_navigation": False,  # don't allow sidebar to collapse,
    "site_url": "https://fraunhoferiwes.github.io/foxes-opt.docs/index.html",
    "repo_url": "https://github.com/FraunhoferIWES/foxes-opt",
    "icon": {"repo": "fontawesome/brands/github", "edit": "material/file-edit-outline"},
    "palette": {"primary": "teal"},
    "toc_title_is_page_title": True,
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
# html_static_path = ["_static"]

# custom.css is inside one of the html_static_path folders (e.g. _static)
# html_css_files = ["custom.css"]

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}


# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = "foxesdoc"


# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',
    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',
    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',
    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (
        master_doc,
        "foxes-opt.tex",
        "foxes-opt Documentation",
        "Fraunhofer IWES",
        "manual",
    ),
]


# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [(master_doc, "foxes-opt", "foxes-opt Documentation", [author], 1)]


# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (
        master_doc,
        "foxes-opt",
        "foxes-opt Documentation",
        author,
        "foxes-opt",
        "Farm Optimization and eXtended yield Evaluation Software",
        "Miscellaneous",
    ),
]


# -- Options for Epub output -------------------------------------------------

# Bibliographic Dublin Core info.
epub_title = project

# The unique identifier of the text. This can be a ISBN number
# or the project homepage.
#
# epub_identifier = ''

# A unique identification for the text.
#
# epub_uid = ''

# A list of files that should not be packed into the epub file.
epub_exclude_files = ["search.html"]

# -- python_apigen configuration -------------------------------------------------

python_apigen_modules = {
    "foxes_opt.variables": "_foxes_opt/variables/",
    "foxes_opt.constants": "_foxes_opt/constants/",
    "foxes_opt.algorithms": "_foxes_opt/algorithms/",
    "foxes_opt.algorithms.downwind": "_foxes_opt/algorithms/downwind/",
    "foxes_opt.algorithms.downwind.models": "_foxes_opt/algorithms/downwind/models/",
    "foxes_opt.algorithms.iterative": "_foxes_opt/algorithms/iterative/",
    "foxes_opt.algorithms.iterative.models": "_foxes_opt/algorithms/iterative/models/",
    "foxes_opt.algorithms.sequential": "_foxes_opt/algorithms/sequential/",
    "foxes_opt.algorithms.sequential.models": "_foxes_opt/algorithms/sequential/models/",
    "foxes_opt.config": "_foxes_opt/config/",
    "foxes_opt.core": "_foxes_opt/core/",
    "foxes_opt.data": "_foxes_opt/data/",
    "foxes_opt.engines": "_foxes_opt/engines/",
    "foxes_opt.input.farm_layout": "_foxes_opt/input/farm_layout/",
    "foxes_opt.input.states": "_foxes_opt/input/states/",
    "foxes_opt.input.states.create": "_foxes_opt/input/states/create/",
    "foxes_opt.input.yaml": "_foxes_opt/input/yaml/",
    "foxes_opt.input.yaml.windio": "_foxes_opt/input/yaml/windio/",
    "foxes_opt.output": "_foxes_opt/output/",
    "foxes_opt.output.flow_plots_2d": "_foxes_opt/output/flow_plots_2d/",
    "foxes_opt.output.seq_plugins": "_foxes_opt/output/seq_plugins/",
    "foxes_opt.models": "_foxes_opt/models/",
    "foxes_opt.models.farm_controllers": "_foxes_opt/models/farm_controllers/",
    "foxes_opt.models.farm_models": "_foxes_opt/models/farm_models/",
    "foxes_opt.models.partial_wakes": "_foxes_opt/models/partial_wakes/",
    "foxes_opt.models.point_models": "_foxes_opt/models/point_models/",
    "foxes_opt.models.rotor_models": "_foxes_opt/models/rotor_models/",
    "foxes_opt.models.turbine_models": "_foxes_opt/models/turbine_models/",
    "foxes_opt.models.turbine_types": "_foxes_opt/models/turbine_types/",
    "foxes_opt.models.vertical_profiles": "_foxes_opt/models/vertical_profiles/",
    "foxes_opt.models.axial_induction": "_foxes_opt/models/axial_induction",
    "foxes_opt.models.ground_models": "_foxes_opt/models/ground_models",
    "foxes_opt.models.wake_deflections": "_foxes_opt/models/wake_deflections",
    "foxes_opt.models.wake_frames": "_foxes_opt/models/wake_frames/",
    "foxes_opt.models.wake_models": "_foxes_opt/models/wake_models/",
    "foxes_opt.models.wake_models.induction": "_foxes_opt/models/wake_models/induction/",
    "foxes_opt.models.wake_models.wind": "_foxes_opt/models/wake_models/wind/",
    "foxes_opt.models.wake_models.ti": "_foxes_opt/models/wake_models/ti/",
    "foxes_opt.models.wake_superpositions": "_foxes_opt/models/wake_superpositions/",
    "foxes_opt.utils": "_foxes_opt/utils/",
    "foxes_opt.utils.abl": "_foxes_opt/utils/abl",
    "foxes_opt.utils.geom2d": "_foxes_opt/utils/geom2d/",
    "foxes_opt.utils.two_circles": "_foxes_opt/utils/two_circles/",
    "foxes_opt.utils.abl.neutral": "_foxes_opt/utils/abl/neutral/",
    "foxes_opt.utils.abl.stable": "_foxes_opt/utils/abl/stable/",
    "foxes_opt.utils.abl.unstable": "_foxes_opt/utils/abl/unstable/",
    "foxes_opt.utils.abl.sheared": "_foxes_opt/utils/abl/sheared/",
}

# myst-nb parameters

myst_enable_extensions = [
    "amsmath",
    "colon_fence",
    "deflist",
    "dollarmath",
    "html_image",
]

nb_execution_mode = "auto"
nb_execution_timeout = 300
nb_ipywidgets_js = {
    "https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js": {
        "integrity": "sha256-Ae2Vz/4ePdIu6ZyI/5ZGsYnb+m0JlOmKPjt6XZ9JJkA=",
        "crossorigin": "anonymous",
    },
    "https://cdn.jsdelivr.net/npm/@jupyter-widgets/html-manager@*/dist/embed-amd.js": {
        "data-jupyter-widgets-cdn": "https://cdn.jsdelivr.net/npm/",
        "crossorigin": "anonymous",
    },
}
# nb_render_image_options = {"width": "200px"}
# application/vnd.plotly.v1+json and application/vnd.bokehjs_load.v0+json
suppress_warnings = ["mystnb.unknown_mime_type"]
